# Generated by Django 4.2.7 on 2025-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_payment_options_payment_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("airtel", "Airtel Money"),
                    ("mtn", "MTN Mobile Money"),
                    ("stripe", "Stripe"),
                    ("cash", "Cash"),
                    ("delivery", "Payment on Delivery"),
                ],
                max_length=20,
            ),
        ),
    ]
