# Generated by Django 4.2.7 on 2025-11-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_alter_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="room_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
