# Generated by Django 4.2.7 on 2025-12-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Inquiry",
                "verbose_name_plural": "Customer Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("order_status_update", "Order Status Update"),
                            ("product_update", "Product Update"),
                            ("stock_update", "Stock Update"),
                            ("inquiry_resolved", "Inquiry Resolved"),
                        ],
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(max_length=50, verbose_name="Target Model"),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="Target ID")),
                (
                    "changes",
                    models.JSONField(
                        help_text="JSON object containing the changes made",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Audit Log",
                "verbose_name_plural": "Staff Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["staff_member", "-timestamp"],
                        name="staff_dashb_staff_m_e8567d_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="staff_dashb_action_5e34ea_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="staff_dashb_timesta_c648b2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Is Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revoked At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_approvals_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_approval",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Approval",
                "verbose_name_plural": "Staff Approvals",
                "indexes": [
                    models.Index(
                        fields=["user"], name="staff_dashb_user_id_3646be_idx"
                    ),
                    models.Index(
                        fields=["is_approved"], name="staff_dashb_is_appr_243704_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InquiryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="staff_dashboard.customerinquiry",
                        verbose_name="Inquiry",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Staff Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Response",
                "verbose_name_plural": "Inquiry Responses",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["inquiry", "created_at"],
                        name="staff_dashb_inquiry_9e2464_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customerinquiry",
            index=models.Index(
                fields=["customer", "status"], name="staff_dashb_custome_565d77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerinquiry",
            index=models.Index(
                fields=["status", "-created_at"], name="staff_dashb_status_99b639_idx"
            ),
        ),
    ]
