# Generated by Django 5.1.7 on 2025-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("admin", "Admin")],
                default="client",
                max_length=10,
            ),
        ),
    ]
