# Generated by Django 4.2.7 on 2025-11-12 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
