# Generated by Django 4.2.7 on 2025-12-15 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_sales", "Daily Sales Report"),
                            ("order_status", "Order Status Report"),
                            ("product_sales", "Product Sales Report"),
                            ("stock_level", "Stock Level Report"),
                            ("customer_growth", "Customer Growth Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(help_text="Comma-separated email addresses"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("next_send", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_send"],
            },
        ),
        migrations.CreateModel(
            name="ReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_sales", "Daily Sales Report"),
                            ("order_status", "Order Status Report"),
                            ("product_sales", "Product Sales Report"),
                            ("stock_level", "Stock Level Report"),
                            ("customer_growth", "Customer Growth Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("data", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "date_from", "date_to"],
                        name="reports_rep_report__92ab15_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="reports_rep_expires_9e7899_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "export_format",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="reports_rep_user_id_910962_idx",
                    )
                ],
            },
        ),
    ]
