# Generated by Django 5.1.7 on 2025-04-05 03:11

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_options_alter_checkout_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[home.models.validate_zambian_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[home.models.validate_zambian_phone], verbose_name='Phone Number'),
        ),
    ]
