# Generated by Django 5.1.7 on 2025-04-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_status_alter_sale_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_profile.jpg', null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
    ]
