# Generated by Django 5.1.7 on 2025-04-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/Default_profile.jpg', null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
    ]
