# Generated by Django 5.1.7 on 2025-04-06 18:41

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[home.models.validate_zambian_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_profile.jpg', null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
    ]
