# Generated by Django 5.1.7 on 2025-04-08 02:22

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_checkout_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[home.models.validate_zambian_phone], verbose_name='Phone Number'),
        ),
    ]
