# Generated by Django 5.1.7 on 2025-04-08 02:36

import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_checkout_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[home.models.validate_zambian_phone], verbose_name='Phone Number'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='home_produc_seller__76153e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='home_produc_created_1c99e2_idx'),
        ),
    ]
