# Generated by Django 5.1.7 on 2025-04-11 19:58

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_checkout_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={},
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[home.models.validate_zambian_phone], verbose_name='Phone Number'),
        ),
    ]
