# Generated by Django 4.2.7 on 2025-10-22 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0015_alter_checkout_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Approval Status",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved At"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved By",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
    ]
