# Generated by Django 4.2.7 on 2025-11-09 11:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0018_alter_checkout_phone_number_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="home.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Reservation",
                "verbose_name_plural": "Stock Reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Stock"),
                            ("restock", "Restocked"),
                            ("sale", "Sold"),
                            ("return", "Returned"),
                            ("adjustment", "Manual Adjustment"),
                            ("reservation", "Reserved"),
                            ("reservation_released", "Reservation Released"),
                            ("damaged", "Damaged/Lost"),
                        ],
                        max_length=30,
                        verbose_name="Change Type",
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="Positive for additions, negative for reductions",
                        verbose_name="Quantity Change",
                    ),
                ),
                (
                    "stock_before",
                    models.PositiveIntegerField(verbose_name="Stock Before"),
                ),
                (
                    "stock_after",
                    models.PositiveIntegerField(verbose_name="Stock After"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_changes",
                        to="home.order",
                        verbose_name="Related Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="home.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_changes",
                        to="home.stockreservation",
                        verbose_name="Related Reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock History",
                "verbose_name_plural": "Stock Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["user", "status"], name="home_stockr_user_id_55e710_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["product", "status"], name="home_stockr_product_7b7c5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["expires_at", "status"], name="home_stockr_expires_00a524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockhistory",
            index=models.Index(
                fields=["product", "-created_at"], name="home_stockh_product_7dbef6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockhistory",
            index=models.Index(
                fields=["change_type", "-created_at"],
                name="home_stockh_change__9fae4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockhistory",
            index=models.Index(
                fields=["changed_by", "-created_at"],
                name="home_stockh_changed_06030a_idx",
            ),
        ),
    ]
