# Generated by Django 4.2.7 on 2025-11-11 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0019_alter_checkout_phone_number_stockreservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Store Name")),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "city",
                    models.CharField(
                        default="Lusaka", max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be a valid Zambian number (e.g., 0971234567 or +260971234567).",
                                regex="^(09|\\+2609|2609)[0-9]{8}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be a valid Zambian number (e.g., 0971234567 or +260971234567).",
                                regex="^(09|\\+2609|2609)[0-9]{8}$",
                            )
                        ],
                        verbose_name="WhatsApp Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        help_text="e.g., Mon-Fri: 9AM-6PM, Sat: 10AM-4PM",
                        verbose_name="Opening Hours",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_pickup_point",
                    models.BooleanField(
                        default=True, verbose_name="Available as Pickup Point"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Store Manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
                "ordering": ["city", "name"],
            },
        ),
    ]
