# Generated by Django 4.2.7 on 2025-11-12 04:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_alter_checkout_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="static_image",
            field=models.CharField(
                blank=True,
                help_text="Path to image in static folder (e.g., 'images/Jewerly/watch1.jpg')",
                max_length=500,
                null=True,
                verbose_name="Static Image Path",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
    ]
