# Generated by Django 4.2.7 on 2025-11-13 14:32

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_product_static_image_alter_checkout_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Full Delivery Address"
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[("inside", "Lusaka City"), ("outside", "Outside Lusaka")],
                max_length=10,
                null=True,
                verbose_name="Delivery Area",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="room_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Delivery Address"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Courier is on the way"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
