# Generated by Django 4.2.7 on 2025-11-13 14:36

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_checkout_delivery_address_alter_checkout_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
    ]
