# Generated by Django 4.2.7 on 2025-11-13 17:11

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_alter_checkout_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Delivery Instructions"
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="room_number",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Street Address / Building / Landmark",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a valid Zambian number (e.g., 0971234567 or +260971234567).",
                        regex="^(09|\\+2609|2609)[0-9]{8}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
