# Generated by Django 4.2.7 on 2025-11-14 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0026_alter_checkout_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="ProductManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="manuals/products/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                        verbose_name="Manual File",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Display Filename"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="File Size (bytes)"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual",
                        to="home.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_product_manuals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Manual",
                "verbose_name_plural": "Product Manuals",
            },
        ),
        migrations.CreateModel(
            name="PlatformGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Guide Title")),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("getting_started", "Getting Started"),
                            ("shopping", "Shopping"),
                            ("checkout", "Checkout & Payment"),
                            ("account", "Account Management"),
                            ("seller", "Selling on Platform"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief summary shown in guide listings",
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full guide content (supports HTML)",
                        verbose_name="Guide Content",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Display prominently on Help Center homepage",
                        verbose_name="Featured Guide",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View Count"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_guides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Guide",
                "verbose_name_plural": "Platform Guides",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuideAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="manuals/guides/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Attachment File",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("pdf", "PDF")],
                        max_length=10,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="home.platformguide",
                        verbose_name="Guide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Attachment",
                "verbose_name_plural": "Guide Attachments",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="platformguide",
            index=models.Index(fields=["slug"], name="home_platfo_slug_c612e2_idx"),
        ),
        migrations.AddIndex(
            model_name="platformguide",
            index=models.Index(
                fields=["category", "is_published"],
                name="home_platfo_categor_8d4aa3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformguide",
            index=models.Index(
                fields=["featured", "is_published"],
                name="home_platfo_feature_20a080_idx",
            ),
        ),
    ]
