# Generated by Django 4.2.7 on 2025-11-14 16:51

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_alter_checkout_phone_number_productmanual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="platformguide",
            name="category",
            field=models.CharField(
                choices=[
                    ("getting_started", "Getting Started"),
                    ("shopping", "Shopping"),
                    ("checkout", "Checkout & Payment"),
                    ("account", "Account Management"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
                verbose_name="Category",
            ),
        ),
    ]
