# Generated by Django 4.2.7 on 2025-11-15 05:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_alter_checkout_phone_number_chatsession_chatmessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
    ]
