# Generated by Django 4.2.7 on 2025-12-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0030_alter_checkout_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for order cancellation or failure",
                null=True,
                verbose_name="Cancellation Reason",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cancelled By",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[home.models.validate_zambian_phone],
                verbose_name="Phone Number",
            ),
        ),
    ]
