# Generated by Django 4.2.7 on 2025-10-26 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
